feat(01-building-blocks): change from faild to successful step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -14,7 +14,9 @@ jobs:
         steps:
             - name: Faild step
               run: |
-                echo "I will fail"
-                exit 1
+                # echo "I will fail"
+                # exit 1
+                echo "I will succeed"
+                exit 0
             - name: Say goodbye
               run: echo "Goodbye!"
